title: Title
url: https://www.open.gov.sg
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#0537cb"
  secondary-color: "#3d69bf"
  media-colors:
    - title: media-color-one
      color: "#0c66b6"
    - title: media-color-two
      color: "#4392dc"
    - title: media-color-three
      color: "#2883bb"
    - title: media-color-four
      color: "#5d9ffa"
    - title: media-color-five
      color: "#1567d5"
description: An Isomer site of the Singapore Government
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d7xp6n784akya.amplifyapp.com
prod: https://master.d7xp6n784akya.amplifyapp.com
facebook-pixel: ""
resources_name: resources
shareicon: /images/isomer-logo.svg
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
